spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_NAME:policeman}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
springdoc:
  swagger-ui:
    operationsSorter: method
  api-docs:
    path: /v2/api-docs
jwt:
  secret: ${JWT_SECRET:P7iJCxDNB0q0rP0UIBQqoT8wXuA1NZ8abqNXm5AFTMbbimG5sgFkpyrzQQJEnXxGA94id6ZvUn8cEJR0NBRU5A==}
